### ISSUE TITLE
Implicit dependency on the check module

### ISSUE THREAD

**Issue by tsdorsey** [aslagle/reactive-table#397]
In cleaning up the package list in a Meteor 1.2.1 app I removed the `check` module because we do not use it (it's used by `meteor-base` but it declares a dependency).

Reactive table will fail if the `check` module is removed (it removes `check` from the global namespace ) [upgrade guide](https://quip.com/RXFlAk9Rc2xI#dbfACAg4mCA)

Here is the callstack.

```
Exception from sub [REDACTED] id [REDACTED] ReferenceError: check is not defined
    at [object Object].<anonymous> (/myApp/.meteor/local/build/programs/server/packages/aslagle_reactive-table.js:248:7)
    at /myApp/.meteor/local/build/programs/server/packages/matb33_collection-hooks.js:299:21
    at [object Object]._.extend.withValue (/myApp/.meteor/local/build/programs/server/packages/meteor.js:1021:17)
    at [object Object]._handler (/myApp/.meteor/local/build/programs/server/packages/matb33_collection-hooks.js:298:28)
    at maybeAuditArgumentChecks (/myApp/.meteor/local/build/programs/server/packages/ddp-server.js:1785:12)
    at [object Object]._.extend._runHandler (/myApp/.meteor/local/build/programs/server/packages/ddp-server.js:1167:17)
    at [object Object].subscriptionProto._runHandler (/myApp/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:2692:24)
    at [object Object]._.extend._startSubscription (/myApp/.meteor/local/build/programs/server/packages/ddp-server.js:994:9)
    at [object Object]._.extend.protocol_handlers.sub (/myApp/.meteor/local/build/programs/server/packages/ddp-server.js:788:12)
    at /myApp/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:2555:34
    at [object Object]._.extend.withValue (/myApp/.meteor/local/build/programs/server/packages/meteor.js:1021:17)
    at [object Object].sessionProto.protocol_handlers.sub (/myApp/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:2554:44)
    at /myApp/.meteor/local/build/programs/server/packages/ddp-server.js:729:85
```

**Comment by aslagle** [comment]
Thanks, I'll fix this.

**Comment by aslagle** [comment]
Actually, looks like I already have it as explicit dependency - https://github.com/aslagle/reactive-table/blob/master/package.js#L17. Are you using an older version?

**Comment by tsdorsey** [comment]
Ugh. Yeah. Sorry about that. Using 0.8.12. Upgraded to 0.8.31 and it's working as expected.
